// <auto-generated />
using System;
using BE_Healthcare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE_Healthcare.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240509185322_Update_Table_Appointment_v3")]
    partial class Update_Table_Appointment_v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BE_Healthcare.Data.Entities.Appointment", b =>
                {
                    b.Property<int>("IdAppointment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("IdDoctor")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdUser")
                        .HasColumnType("char(36)");

                    b.Property<string>("Issue")
                        .HasColumnType("longtext");

                    b.Property<double?>("Price")
                        .HasColumnType("double");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("Type")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isDoctorCancel")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isUserCancel")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdAppointment");

                    b.HasIndex("IdDoctor");

                    b.HasIndex("IdUser");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            IdAppointment = 5,
                            Date = new DateTime(2024, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = "11:00",
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            IdUser = new Guid("9117c626-c3d0-4d14-b345-d70d85268623"),
                            Issue = "Tôi đang gặp phải vấn đề về da liễu, tôi cần bác sĩ kiểm tra và tư vấn giúp tôi.",
                            StartTime = "10:00",
                            Status = 1,
                            Type = false,
                            isDoctorCancel = false,
                            isUserCancel = false
                        },
                        new
                        {
                            IdAppointment = 6,
                            Date = new DateTime(2024, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = "10:00",
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            IdUser = new Guid("bfa4b5ec-1ad8-4676-8871-122749af64e4"),
                            Issue = "Tôi đang gặp phải vấn đề về ruột thừa, tôi cần bác sĩ kiểm tra và tư vấn giúp tôi.",
                            StartTime = "9:00",
                            Status = 1,
                            Type = false,
                            isDoctorCancel = false,
                            isUserCancel = false
                        },
                        new
                        {
                            IdAppointment = 7,
                            Date = new DateTime(2024, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = "16:00",
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            IdUser = new Guid("9117c626-c3d0-4d14-b345-d70d85268623"),
                            Issue = "Toi bi dau bung",
                            StartTime = "15:00",
                            Status = 1,
                            Type = false,
                            isDoctorCancel = false,
                            isUserCancel = false
                        },
                        new
                        {
                            IdAppointment = 8,
                            Date = new DateTime(2024, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = "17:00",
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            IdUser = new Guid("9117c626-c3d0-4d14-b345-d70d85268623"),
                            Issue = "Toi bi dau bung non",
                            StartTime = "16:00",
                            Status = 1,
                            Type = false,
                            isDoctorCancel = false,
                            isUserCancel = false
                        },
                        new
                        {
                            IdAppointment = 9,
                            Date = new DateTime(2024, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = "9:00",
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            IdUser = new Guid("9117c626-c3d0-4d14-b345-d70d85268623"),
                            Issue = "Toi bi dau bung non",
                            StartTime = "8:00",
                            Status = 1,
                            Type = false,
                            isDoctorCancel = false,
                            isUserCancel = false
                        });
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.Certificate", b =>
                {
                    b.Property<int>("IdCertificate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid?>("IdDoctor")
                        .HasColumnType("char(36)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("StatusVerified")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("IdCertificate");

                    b.HasIndex("IdDoctor");

                    b.ToTable("Certificates");

                    b.HasData(
                        new
                        {
                            IdCertificate = 1,
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            Image = "https://hellobacsi.com/care/bac-si/bsckii-tran-thi-hoai-huong-646/",
                            Name = "Hội viên chi hội Da liễu Hồ Chí Minh",
                            StatusVerified = 1,
                            Year = 2020
                        },
                        new
                        {
                            IdCertificate = 2,
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            Image = "https://hellobacsi.com/care/bac-si/bsckii-tran-thi-hoai-huong-646/",
                            Name = "Hội viên Hội Da liễu Việt Nam",
                            StatusVerified = 1,
                            Year = 2022
                        });
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.Doctor", b =>
                {
                    b.Property<Guid>("IdDoctor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DurationPerAppointment")
                        .HasColumnType("int");

                    b.Property<int?>("IdSpecialty")
                        .HasColumnType("int");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("char(36)");

                    b.Property<string>("NameClinic")
                        .HasColumnType("longtext");

                    b.Property<double?>("Price")
                        .HasColumnType("double");

                    b.Property<int?>("StatusVerified")
                        .HasColumnType("int");

                    b.Property<string>("WorkingTimeEnd")
                        .HasColumnType("longtext");

                    b.Property<string>("WorkingTimeStart")
                        .HasColumnType("longtext");

                    b.Property<int?>("YearExperience")
                        .HasColumnType("int");

                    b.HasKey("IdDoctor");

                    b.HasIndex("IdSpecialty");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            Description = "Bác sĩ Chuyên khoa I Trần Thị Hoài Hương nguyên là Phó Trưởng khoa Lâm sàng 1 tại Bệnh viện Da liễu TP.HCM.\r\n\r\nVề chuyên môn, bác sĩ chuyên thăm khám và điều trị các vấn đề bệnh lý chuyên sâu về da, bệnh da ở trẻ cũng như các phương pháp thẩm mỹ da liễu.\r\n\r\n\r\nBác sĩ cũng là gương mặt quen thuộc trong những hội nghị hội thảo về Da liễu. Với nền tảng chuyên môn hơn 20 năm, bác sĩ còn được biết đến với thái độ tận tình tận tâm, luôn sẵn sàng tư vấn hỗ trợ bệnh nhân các vấn đề bệnh lý cũng như trao đổi về các liệu pháp thẩm mỹ hiệu quả phù hợp.",
                            DurationPerAppointment = 1,
                            IdSpecialty = 7,
                            IdUser = new Guid("6d2fc8cc-cbfa-401d-aef5-2d1588751d32"),
                            NameClinic = "Phòng khám bác sĩ Hương",
                            Price = 500000.0,
                            StatusVerified = 1,
                            WorkingTimeEnd = "17:00",
                            WorkingTimeStart = "08:00",
                            YearExperience = 5
                        },
                        new
                        {
                            IdDoctor = new Guid("954d0f01-a006-443a-957d-3d1165b79ee7"),
                            Description = "Tiến sĩ - Bác sĩ Vũ Thái Hà có gần 20 năm kinh nghiệm trong việc tư vấn và điều trị các vấn đề về da liễu như nám, mụn, lão hóa da,…\r\n\r\nVề quá trình đào tạo, bác sĩ tốt nghiệp Bác sĩ nội trú Da liễu, tốt nghiệp bậc Thạc sĩ tại trường Đại học Y Hà Nội. Sau đó, bác sĩ có khoảng thời gian thực tập tại Pháp về phương pháp điều trị các bệnh về da liễu, bệnh về tóc, bệnh về móng.\r\n\r\n\r\nBác sĩ hiện đang đảm nhận vai trò Trưởng khoa Nghiên cứu và Ứng dụng công nghệ tế bào gốc tại Bệnh viện Da liễu Trung Ương. Bên cạnh đó, bác sĩ cũng là người phụ trách chuyên môn tại Phòng khám Da liễu Thái Hà.\r\n\r\nVới nền tảng chuyên môn cực kỳ vững chắc, bác sĩ chuyên thăm khám và điều trị các vấn đề bệnh lý liên quan đến da: viêm da cơ địa, viêm da tiếp xúc, viêm da dầu, thủy đậu, nám da, nám da,...Bên cạnh đó, bác sĩ cũng nhận tư vấn các vấn đề về sẹo, vấn đề về mụn, tình trạng lão hóa da, bớt sắc tố.",
                            DurationPerAppointment = 1,
                            IdSpecialty = 5,
                            IdUser = new Guid("9f12c430-de83-4910-92ac-704bffefaab2"),
                            NameClinic = "Phòng khám Bác sĩ Thái Hà",
                            Price = 600000.0,
                            StatusVerified = 1,
                            WorkingTimeEnd = "17:00",
                            WorkingTimeStart = "07:00",
                            YearExperience = 8
                        },
                        new
                        {
                            IdDoctor = new Guid("2536a049-6c0d-45fc-a0d6-ea107731c983"),
                            Description = "Tiến sĩ - Bác sĩ Trần Thịnh có gần 40 năm kinh nghiệm thăm khám và điều trị các vấn đề Da liễu. Tiến sĩ nguyên là Trưởng khoa Da liễu - Bệnh viện Da liễu TP.HCM và hiện đang là người điều hành phòng khám Chuyên khoa Da liễu Trần Thịnh.\r\n\r\nVề quá trình đào tạo, tiến sĩ tốt nghiệp chuyên ngành Da liễu tại trường Đại học Y Dược TP. HCM. Sau khi tốt nghiệp, tiến sĩ được giữ lại trường và đảm nhiệm vai trò bác sĩ, cán bộ phòng Khoa học kỹ thuật khoa Y. Đến năm 2009, dù đã là người dày dặn kinh nghiệm trong ngành, bác sĩ tiếp tục dành thời gian học thêm chuyên ngành về Quản lý Y tế tại trường Đại học Y Dược.\r\n\r\n\r\nNgoài cương vị bác sĩ, giai đoạn từ năm 1991 - 1999, tiến sĩ còn đảm đương nhiều vai trò quan trọng tại bệnh viện Da liễu. Trong đó có việc tham gia phụ trách chương trình kiểm soát bệnh lây qua tình dục và AIDS tại TP.HCM cũng như đóng góp vào quá trình đào tạo nguồn lực kế cận với vai trò giảng viên tại các trường đại học.\r\n\r\nNăm 2010, tiến sĩ Trần Thịnh đã nhận được bằng khen từ Bộ trưởng Bộ Y tế về những thành tựu có được. Xuyên suốt quá trình sự nghiệp, tiến sĩ được biết đến là một trong những chuyên gia vững về trình độ chuyên môn, tận tâm tận tình trong quá trình thăm khám.",
                            DurationPerAppointment = 1,
                            IdSpecialty = 1,
                            IdUser = new Guid("efaaf180-4211-45d1-9b08-f085f19cb451"),
                            NameClinic = "Phòng khám bác sĩ Thịnh",
                            Price = 400000.0,
                            StatusVerified = 1,
                            WorkingTimeEnd = "18:00",
                            WorkingTimeStart = "08:00",
                            YearExperience = 7
                        });
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.MedicalSpecialty", b =>
                {
                    b.Property<int>("IdSpecialty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdSpecialty");

                    b.ToTable("MedicalSpecialties");

                    b.HasData(
                        new
                        {
                            IdSpecialty = 1,
                            Name = "Internal Medicine"
                        },
                        new
                        {
                            IdSpecialty = 2,
                            Name = "General Surgery"
                        },
                        new
                        {
                            IdSpecialty = 3,
                            Name = "Obstetrics and Gynecology"
                        },
                        new
                        {
                            IdSpecialty = 4,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            IdSpecialty = 5,
                            Name = "Emergency Medicine"
                        },
                        new
                        {
                            IdSpecialty = 6,
                            Name = "Dermatology"
                        },
                        new
                        {
                            IdSpecialty = 7,
                            Name = "Dentistry"
                        },
                        new
                        {
                            IdSpecialty = 8,
                            Name = "Plastic Surgery"
                        },
                        new
                        {
                            IdSpecialty = 9,
                            Name = "Nuclear Medicine"
                        },
                        new
                        {
                            IdSpecialty = 10,
                            Name = "Cardiology"
                        },
                        new
                        {
                            IdSpecialty = 11,
                            Name = "Pulmonology"
                        },
                        new
                        {
                            IdSpecialty = 12,
                            Name = "Gastroenterology"
                        },
                        new
                        {
                            IdSpecialty = 13,
                            Name = "Hematology"
                        },
                        new
                        {
                            IdSpecialty = 14,
                            Name = "Endocrinology"
                        },
                        new
                        {
                            IdSpecialty = 15,
                            Name = "Public Health"
                        },
                        new
                        {
                            IdSpecialty = 16,
                            Name = "Preventive Medicine"
                        },
                        new
                        {
                            IdSpecialty = 17,
                            Name = "Psychiatry"
                        },
                        new
                        {
                            IdSpecialty = 18,
                            Name = "Traditional Medicine"
                        });
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("IdRole");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRole = 1,
                            Name = "User"
                        },
                        new
                        {
                            IdRole = 2,
                            Name = "Doctor"
                        },
                        new
                        {
                            IdRole = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.TimeOff", b =>
                {
                    b.Property<int>("IdTimeOff")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("IdDoctor")
                        .HasColumnType("char(36)");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("IdTimeOff");

                    b.HasIndex("IdDoctor");

                    b.ToTable("TimeOffs");

                    b.HasData(
                        new
                        {
                            IdTimeOff = 1,
                            Date = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = "10:00",
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            Reason = "Busy with family",
                            StartTime = "08:00",
                            Status = 1
                        },
                        new
                        {
                            IdTimeOff = 2,
                            Date = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = "16:00",
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            Reason = "Busy with family",
                            StartTime = "15:00",
                            Status = 1
                        },
                        new
                        {
                            IdTimeOff = 3,
                            Date = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = "13:00",
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            StartTime = "11:00",
                            Status = 2
                        },
                        new
                        {
                            IdTimeOff = 4,
                            Date = new DateTime(2024, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = "15:00",
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            Reason = "Busy with family",
                            StartTime = "13:00",
                            Status = 1
                        });
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.TrainingProcess", b =>
                {
                    b.Property<int>("IdTrainingProcess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdDoctor")
                        .HasColumnType("char(36)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.Property<int?>("StatusVerified")
                        .HasColumnType("int");

                    b.HasKey("IdTrainingProcess");

                    b.HasIndex("IdDoctor");

                    b.ToTable("TrainingProcesses");

                    b.HasData(
                        new
                        {
                            IdTrainingProcess = 1,
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            Major = "Tốt nghiệp Bác sĩ Chuyên khoa II, chuyên ngành Da liễu",
                            SchoolName = "Đại học Y Dược TP.HCM",
                            StatusVerified = 1
                        },
                        new
                        {
                            IdTrainingProcess = 2,
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            Major = "Tốt nghiệp Bác sĩ Chuyên khoa I, chuyên ngành Da liễu",
                            SchoolName = "Đại học Y Dược TP.HCM",
                            StatusVerified = 1
                        },
                        new
                        {
                            IdTrainingProcess = 3,
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            Major = "Tốt nghiệp Bác sĩ Đa khoa",
                            SchoolName = "Đại học Y Dược TP.HCM",
                            StatusVerified = 1
                        },
                        new
                        {
                            IdTrainingProcess = 4,
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            Major = "Tham gia lớp Sơ bộ DInh dưỡng",
                            SchoolName = "Đại học Y khoa Phạm Ngọc Thạch",
                            StatusVerified = 1
                        });
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.User", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("OTPCreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OTPVerification")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("ReasonLockAccount")
                        .HasColumnType("longtext");

                    b.Property<int>("idRole")
                        .HasColumnType("int");

                    b.HasKey("IdUser");

                    b.HasIndex("idRole");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            IdUser = new Guid("9117c626-c3d0-4d14-b345-d70d85268623"),
                            Email = "nguyenquocthanh268@gmail.com",
                            IsLocked = false,
                            IsVerified = true,
                            Name = "Nguyen Quoc Thanh",
                            OTPCreatedAt = new DateTime(2024, 5, 9, 18, 53, 21, 891, DateTimeKind.Utc).AddTicks(5682),
                            OTPVerification = "123456",
                            PasswordHash = new byte[] { 241, 184, 9, 204, 85, 191, 111, 81, 144, 141, 154, 53, 61, 79, 206, 30, 94, 54, 119, 44, 158, 152, 238, 158, 41, 200, 68, 19, 23, 7, 212, 249 },
                            PasswordSalt = new byte[] { 228, 62, 240, 204, 152, 236, 46, 204, 225, 195, 192, 205, 180, 128, 207, 198, 74, 12, 41, 161, 165, 74, 22, 229, 88, 144, 120, 199, 215, 126, 75, 250, 26, 82, 141, 7, 194, 124, 132, 247, 113, 177, 227, 247, 180, 58, 240, 252, 5, 118, 216, 219, 43, 111, 32, 27, 162, 239, 137, 113, 183, 34, 199, 83 },
                            idRole = 1
                        },
                        new
                        {
                            IdUser = new Guid("85f97fe1-83e4-4dcc-91ca-367cb29f148e"),
                            Email = "buivanhuy@gmail.com",
                            IsLocked = false,
                            IsVerified = true,
                            Name = "Huy Bui",
                            OTPCreatedAt = new DateTime(2024, 5, 9, 18, 53, 21, 891, DateTimeKind.Utc).AddTicks(5703),
                            OTPVerification = "123456",
                            PasswordHash = new byte[] { 241, 184, 9, 204, 85, 191, 111, 81, 144, 141, 154, 53, 61, 79, 206, 30, 94, 54, 119, 44, 158, 152, 238, 158, 41, 200, 68, 19, 23, 7, 212, 249 },
                            PasswordSalt = new byte[] { 228, 62, 240, 204, 152, 236, 46, 204, 225, 195, 192, 205, 180, 128, 207, 198, 74, 12, 41, 161, 165, 74, 22, 229, 88, 144, 120, 199, 215, 126, 75, 250, 26, 82, 141, 7, 194, 124, 132, 247, 113, 177, 227, 247, 180, 58, 240, 252, 5, 118, 216, 219, 43, 111, 32, 27, 162, 239, 137, 113, 183, 34, 199, 83 },
                            idRole = 1
                        },
                        new
                        {
                            IdUser = new Guid("bfa4b5ec-1ad8-4676-8871-122749af64e4"),
                            Email = "anhoang@gmail.com",
                            IsLocked = false,
                            IsVerified = true,
                            Name = "Vo A Hoang",
                            OTPCreatedAt = new DateTime(2024, 5, 9, 18, 53, 21, 891, DateTimeKind.Utc).AddTicks(5718),
                            OTPVerification = "123456",
                            PasswordHash = new byte[] { 241, 184, 9, 204, 85, 191, 111, 81, 144, 141, 154, 53, 61, 79, 206, 30, 94, 54, 119, 44, 158, 152, 238, 158, 41, 200, 68, 19, 23, 7, 212, 249 },
                            PasswordSalt = new byte[] { 228, 62, 240, 204, 152, 236, 46, 204, 225, 195, 192, 205, 180, 128, 207, 198, 74, 12, 41, 161, 165, 74, 22, 229, 88, 144, 120, 199, 215, 126, 75, 250, 26, 82, 141, 7, 194, 124, 132, 247, 113, 177, 227, 247, 180, 58, 240, 252, 5, 118, 216, 219, 43, 111, 32, 27, 162, 239, 137, 113, 183, 34, 199, 83 },
                            idRole = 1
                        },
                        new
                        {
                            IdUser = new Guid("6d2fc8cc-cbfa-401d-aef5-2d1588751d32"),
                            Email = "doctor1@gmail.com",
                            IsLocked = false,
                            IsVerified = true,
                            Name = "BS.CKII Trần Thị Hoài Hương",
                            OTPCreatedAt = new DateTime(2024, 5, 9, 18, 53, 21, 891, DateTimeKind.Utc).AddTicks(5732),
                            OTPVerification = "123456",
                            PasswordHash = new byte[] { 241, 184, 9, 204, 85, 191, 111, 81, 144, 141, 154, 53, 61, 79, 206, 30, 94, 54, 119, 44, 158, 152, 238, 158, 41, 200, 68, 19, 23, 7, 212, 249 },
                            PasswordSalt = new byte[] { 228, 62, 240, 204, 152, 236, 46, 204, 225, 195, 192, 205, 180, 128, 207, 198, 74, 12, 41, 161, 165, 74, 22, 229, 88, 144, 120, 199, 215, 126, 75, 250, 26, 82, 141, 7, 194, 124, 132, 247, 113, 177, 227, 247, 180, 58, 240, 252, 5, 118, 216, 219, 43, 111, 32, 27, 162, 239, 137, 113, 183, 34, 199, 83 },
                            idRole = 2
                        },
                        new
                        {
                            IdUser = new Guid("9f12c430-de83-4910-92ac-704bffefaab2"),
                            Email = "doctor2@gmail.com",
                            IsLocked = false,
                            IsVerified = true,
                            Name = "TS.BS Vũ Thái Hà",
                            OTPCreatedAt = new DateTime(2024, 5, 9, 18, 53, 21, 891, DateTimeKind.Utc).AddTicks(5745),
                            OTPVerification = "123456",
                            PasswordHash = new byte[] { 241, 184, 9, 204, 85, 191, 111, 81, 144, 141, 154, 53, 61, 79, 206, 30, 94, 54, 119, 44, 158, 152, 238, 158, 41, 200, 68, 19, 23, 7, 212, 249 },
                            PasswordSalt = new byte[] { 228, 62, 240, 204, 152, 236, 46, 204, 225, 195, 192, 205, 180, 128, 207, 198, 74, 12, 41, 161, 165, 74, 22, 229, 88, 144, 120, 199, 215, 126, 75, 250, 26, 82, 141, 7, 194, 124, 132, 247, 113, 177, 227, 247, 180, 58, 240, 252, 5, 118, 216, 219, 43, 111, 32, 27, 162, 239, 137, 113, 183, 34, 199, 83 },
                            idRole = 2
                        },
                        new
                        {
                            IdUser = new Guid("efaaf180-4211-45d1-9b08-f085f19cb451"),
                            Email = "doctor3@gmail.com",
                            IsLocked = false,
                            IsVerified = true,
                            Name = "TS.BS Trần Thịnh",
                            OTPCreatedAt = new DateTime(2024, 5, 9, 18, 53, 21, 891, DateTimeKind.Utc).AddTicks(5758),
                            OTPVerification = "123456",
                            PasswordHash = new byte[] { 241, 184, 9, 204, 85, 191, 111, 81, 144, 141, 154, 53, 61, 79, 206, 30, 94, 54, 119, 44, 158, 152, 238, 158, 41, 200, 68, 19, 23, 7, 212, 249 },
                            PasswordSalt = new byte[] { 228, 62, 240, 204, 152, 236, 46, 204, 225, 195, 192, 205, 180, 128, 207, 198, 74, 12, 41, 161, 165, 74, 22, 229, 88, 144, 120, 199, 215, 126, 75, 250, 26, 82, 141, 7, 194, 124, 132, 247, 113, 177, 227, 247, 180, 58, 240, 252, 5, 118, 216, 219, 43, 111, 32, 27, 162, 239, 137, 113, 183, 34, 199, 83 },
                            idRole = 2
                        });
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.WorkingProcess", b =>
                {
                    b.Property<int>("IdWorkingProcess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdDoctor")
                        .HasColumnType("char(36)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.Property<int?>("StatusVerified")
                        .HasColumnType("int");

                    b.Property<string>("Workplace")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdWorkingProcess");

                    b.HasIndex("IdDoctor");

                    b.ToTable("WorkingProcesses");

                    b.HasData(
                        new
                        {
                            IdWorkingProcess = 1,
                            EndYear = 2014,
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            Position = "Bác sĩ Da liễu",
                            StartYear = 2012,
                            StatusVerified = 1,
                            Workplace = "Phòng khám Da liễu Táo Đỏ"
                        },
                        new
                        {
                            IdWorkingProcess = 2,
                            EndYear = 2014,
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            Position = "Nguyên Phó Trưởng khoa Lâm sàng 1",
                            StartYear = 2012,
                            StatusVerified = 1,
                            Workplace = "Bệnh viện Da liễu TP. HCM"
                        },
                        new
                        {
                            IdWorkingProcess = 3,
                            EndYear = 2014,
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            Position = "Trưởng Khoa Dinh Dưỡng",
                            StartYear = 2012,
                            StatusVerified = 1,
                            Workplace = "Bệnh viện Da liễu TP. HCM"
                        },
                        new
                        {
                            IdWorkingProcess = 4,
                            EndYear = 2014,
                            IdDoctor = new Guid("6c2e4c40-ad25-40fa-ad40-4c620f09d9b2"),
                            Position = "Bác sĩ chuyên khoa da liễu, thẩm mỹ da",
                            StartYear = 2012,
                            StatusVerified = 1,
                            Workplace = "Bệnh viện Da liễu TP. HCM"
                        });
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.Appointment", b =>
                {
                    b.HasOne("BE_Healthcare.Data.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("IdDoctor");

                    b.HasOne("BE_Healthcare.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser");

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.Certificate", b =>
                {
                    b.HasOne("BE_Healthcare.Data.Entities.Doctor", "Doctor")
                        .WithMany("Certificates")
                        .HasForeignKey("IdDoctor");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.Doctor", b =>
                {
                    b.HasOne("BE_Healthcare.Data.Entities.MedicalSpecialty", "MedicalSpecialty")
                        .WithMany()
                        .HasForeignKey("IdSpecialty");

                    b.HasOne("BE_Healthcare.Data.Entities.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("BE_Healthcare.Data.Entities.Doctor", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalSpecialty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("BE_Healthcare.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.TimeOff", b =>
                {
                    b.HasOne("BE_Healthcare.Data.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("IdDoctor");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.TrainingProcess", b =>
                {
                    b.HasOne("BE_Healthcare.Data.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("IdDoctor");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.User", b =>
                {
                    b.HasOne("BE_Healthcare.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("idRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.WorkingProcess", b =>
                {
                    b.HasOne("BE_Healthcare.Data.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("IdDoctor");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.Doctor", b =>
                {
                    b.Navigation("Certificates");
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BE_Healthcare.Data.Entities.User", b =>
                {
                    b.Navigation("Doctor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
